version: '3.3'
services:
  moobot-belaui:
    image: $REPO/moobot-belaui:$MOOBOT_VERSION
    #image: $REPO/moobot-belaui-bundled:$MOOBOT_VERSION
    container_name: moobot-belaui
    restart: unless-stopped
    stdin_open: true
    privileged: true
    tty: true
    pid: host
    ipc: host
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENVIRONMENT
      - DOTNET_USE_POLLING_FILE_WATCHER=$POLLING_FILE_WATCHER
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=$GLOBALIZATION
      - REGION=$REGION
      - MOOBOT_VERSION=$MOOBOT_VERSION
      - BELACODER_PATH=$BELACODER_PATH
      - SRTLA_PATH=$SRTLA_PATH
    ports:
      - "5000:80"
    volumes:
      - "./appsettings.json:/app/appsettings.$ENVIRONMENT.json"
      - "./data/BelaUI.json:/app/wwwroot/data/BelaUI.json"
      - "./entrypoint.sh:/entrypoint.sh"
      - "/:/host"
    healthcheck:
      test: curl --fail http://localhost/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
